# Generated by Django 4.2.6 on 2024-03-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bios',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
